#az aks update -n K8Cluster-1 -g Project1 --attach-acr mynewimages
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: tomcat-deployment
   labels:
     type: appserver
spec:
   replicas: 2
   selector:
      matchLabels:
        type: appserver
   template:
      metadata:
        name: tomcat-pod
        labels:
           type: appserver
      spec:
        containers:
          - name: mytomcat
            image: mynewimages.azurecr.io/mytomee:latest
            ports:
              - containerPort: 8080
                hostPort: 9090
...