---
apiVersion: v1
kind: Namespace
metadata:
   name: tomcat-ns
---
apiVersion: v1
kind: Service
metadata:
   name: tomcat-svc
   labels:
      type: appserver
   namespace: tomcat-ns
spec:
  type: LoadBalancer
  selector:
      type: appserver
  ports:
     - targetPort: 8080
       port: 9090
       nodePort: 30010
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: tomcat-deployment
    labels:
       type: appserver
    namespace: tomcat-ns
spec:
   replicas: 2
   selector:
       matchLabels:
             type: appserver
   template:
      metadata:
         name: tomcat-pod
         labels:
            type: appserver
      spec:
         containers:
            - name: mytomcat
              image: tomee
              resources:
                  requests:
                      cpu: "64m"
                      memory: "100Mi"
                  limits:
                     cpu: "128m"
                     memory: "200Mi"
...