---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: mysql-rs
   labels:
      type: db
spec:
   replicas: 3
   selector:
      matchLabels:
           type: db
   template:
      metadata:
           name: mysql-pod
           labels:
                type: db
      spec:
           containers:
              - name: mydb
                image: mysql
                env:
                   - name: MYSQL_ROOT_PASSWORD
                     value: intelliqit
                resources:
                     requests:
                          cpu: "1"
                          memory: "1Gi"
                     limits:
                          cpu: "2"
                          memory: "2Gi"
...
...