---
apiVersion: v1
kind: Namespace
metadata:
   name: test2-ns

---
apiVersion: v1
kind: Pod
metadata: 
   name: mysql-pod
   labels: 
    type: db
    auhtor: intelliqit
   namespace: test2-ns
spec:
  containers:
   - name: mydb
     image: mysql
     env:
      - name: MYSQL_ROOT_PASSWORD
        value: intelliqit
...