---
apiVersion: v1
kind: Service
metadata:
   name: jenkins-na-svc
   labels:
      type: ci-cd
spec:
  type: LoadBalancer
  ports:
     - targetPort: 8080
       port: 8080
       nodePort: 30022
  selector:
      type: ci-cd
--- 
apiVersion: v1
kind: Pod
metadata:
     name: jenkins-na-pod
     labels:
       type: ci-cd
spec:
  containers:
     - name: myjenkins
       image: jenkins/jenkins
  affinity:
      nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
                -  matchExpressions:
                      - key: slave1
                        operator: In
                        values:
                          - intelliqit1
...
                           
      
