---
apiVersion: v1
kind: Service
metadata:
    name: nginx-na-svc
    labels:
      author: intelliqit
spec:
   type: LoadBalancer
   selector:
      type: proxy-server
   ports:
    - targetPort: 80
      port: 80
      nodePort: 30021
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-na-deployment
   labels:
       type: proxy-server
spec:
  replicas: 6
  selector:
      matchLabels:
           type: proxy-server
  template:
     metadata:
         labels:
            type: proxy-server
     spec:
        containers:
          - name: my-nginx
            image: nginx:latest
        affinity:
           nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                      - matchExpressions:
                           - key: slave1
                             operator: In
                             values:
                                - intelliqit1
...
