---
apiVersion: v1
kind: Pod
metadata:
   name: nginx-nodeaffinity-pod
   labels:
       type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
                - matchExpressions:
                     - key: slave2
                       operator: In
                       values:
                          - intelliqit2
...
