---
apiVersion: v1
kind: Service
metadata:
    name: nodeaffinity-svc
    labels:
       app: proxy
spec:
  type: LoadBalancer
  selector:
      app: proxy
  ports:
    - targetPort: 80
      port: 7575
      nodePort: 30022
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodeaffinity-dep
    labels:
        app: proxy
spec:
   replicas: 2
   selector:
      matchLabels:
           app: proxy
   template:
      metadata:
          name: nginx-pod
          labels:
             app: proxy
      spec:
        containers:
           - name: mynginx
             image: nginx
        affinity:
         nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                 nodeSelectorTerms:
                      - matchExpressions:
                           - key: slave1
                             operator: In
                             values:
                                 - intelliqitl
...
