---
apiVersion: v1
kind: Service
metadata:
      name: tomcat-nodeport-svc
spec:
  type: NodePort
  ports:
     - name: tcp
       targetPort: 8080
       port: 8080
       nodePort: 30011
  selector:
     app: appserver
     author: HemanthTech
---
apiVersion: v1
kind: Pod
metadata:
   name: tomcat-pod
   labels:
      app: appserver
      author: HemanthTech
spec:
  containers:
        - name: mytomcat
          image: tomee
...
