---
apiVersion: v1
kind: Namespace
metadata:
   name: tomcat-ns
---
apiVersion: v1
kind: Service
metadata:
   name: tomcat-svc
   labels:
      type: app-server
   namespace: tomcat-ns
spec:
   type: LoadBalancer
   selector:
       type: app-server
   ports:
      - targetPort: 8080
        port: 9090
        nodePort: 30015
---
apiVersion: v1
kind: Pod
metadata:
   name: tomcat-pod
   labels:
      type: app-server
   namespace: tomcat-ns
spec:
   containers:
     - name: mytomcat
       image: tomee
...
