---
apiVersion: v1
kind: Pod
metadata:
     name: httpd-tlrt-pod
     labels:
        type: web-server
spec:
  containers:
     - name: myhttpd
       image: httpd
  tolerations:
        - key: slave1
          operator: Equal
          value: intelliqit1
          effect: NoSchedule
...
