---
apiVersion: v1
kind: Pod
metadata:
   name: tomcat-pod
   labels:
      app: appserver
      author: HemanthTech
spec:
  containers:
        - name: mytomcat
          image: tomee
  tolerations:
       - key: slave1
         operator: Equal
         value: intelliqit1
         effect: NoSchedule
...
