---
apiVersion: v1
kind: Service
metadata:
    name: inmemory-app-svc
    labels:
        app: redis-inmemory-app
        author: intelliqit
spec:
   selector:
     app: redis-inmemory-app
     author: intelliqit
   type: ClusterIP
   ports:
     - targetPort: 6379
       port: 6379
...
