---
apiVersion: v1
kind: Service
metadata:
   name: persistentdb-app-svc
   labels:
      author: intelliqit
spec:
  selector:
     app: postgres-db-app
     author: intelliqit
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
...
