---
apiVersion: v1
kind: Service
metadata:
     name: voting-app-svc
     labels:
        author: intelliqit
spec:
  type: LoadBalancer
  selector:
    app: python-voting-app
    author: intelliqit
  ports:
   - targetPort: 80
     port: 80
     nodePort: 31008
...
