apiVersion: apps/v1
kind: Deployment
metadata:
   name: worker-app-deployment
   labels:
      app: dotnet-worker-app
      author: intelliqit
spec:
  replicas: 2
  selector:
     matchLabels:
         app: dotnet-worker-app
         author: intelliqit
  template:
    metadata:
        name: worker-app-pod
        labels:
           app: dotnet-worker-app
           author: intelliqit
    spec:
       containers:
         - name: worker-app
           image: dockersamples/examplevotingapp_worker
...
